-- https://www.lunarvim.org/docs/configuration/autocommands
-- lvim.autocommands = {
--   {
--     "BufWrite",                         -- see `:h autocmd-events`
--     {                                   -- this table is passed verbatim as `opts` to `nvim_create_autocmd`
--       pattern = { "*.tf", "*.tfvars" }, -- see `:h autocmd-events`
--       command = "setlocal wrap",
--     }
--   },
-- }
