-- vim.pack.add({
--     {
--         src = 'https://github.com/nvim-neo-tree/neo-tree.nvim',
--         version = 'main',
--     },
-- })
--
-- require('neo-tree').setup({
--     close_if_last_window = false,
--     popup_border_style = '',
--     filesystem = {
--         use_libuv_file_watcher = true,
--         follow_current_file = {
--             enabled = true,
--         },
--     },
-- })
