return {
    'nvim-treesitter/nvim-treesitter',
    enabled = true,
    build = ':TSUpdate',
    lazy = false, -- can not be lazy loaded
    opts = {
        auto_install = true,
        ensure_installed = {
            'bash',
            'c',
            'css',
            'cmake',
            'diff',
            'go',
            'hcl',
            'html',
            'javascript',
            'jsdoc',
            'json',
            'lua',
            'luadoc',
            'markdown',
            'markdown_inline',
            'python',
            'query',
            'regex',
            'toml',
            'typescript',
            'terraform',
            'tsx',
            'vim',
            'vimdoc',
            'yaml',
        },
        highlight = {
            enable = true,
        },
        indent = {
            enable = true,
        },
        incremental_selection = {
            enable = true,
            keymaps = {
                init_selection = 'gnn',
                node_incremental = 'grn',
                node_decremental = 'grc',
                scope_incremental = 'grm',
            },
        },
    },
}
