#!/bin/bash

LOG="${HOME}/bspwmrc.log"

####################################################################
# configure second monitor if present
####################################################################

MON1="DisplayPort-0"
MON2="HDMI-A-0"
if xrandr -q | grep -q "${MON2} connected"; then
  xrandr --output "${MON1}" --mode 3840x2160 --rotate normal \
    --output "${MON2}" --mode 2560x1440 --rotate right \
    --right-of "${MON1}" >"${LOG}" 2>&1 &
fi

####################################################################
# enable local fonts
####################################################################

# list discovered fonts: fc-list
# see font paths: xset q
find /usr/share/fonts ~/.local/share/fonts -name fonts.dir | while read -r dir; do
    xset +fp "$(dirname "${dir}")" >"${LOG}" 2>&1 &
done
xset fp rehash >"${LOG}" 2>&1 &
fc-cache -fv >"${LOG}" 2>&1 &

####################################################################
# appearance settings and tweaks
####################################################################

xsetroot -cursor_name left_ptr &
xrdb -merge .Xresources &
# compositing
[ -f "${XDG_CONFIG_HOME}/picom.conf" ] && picom -b >"${LOG}" 2>&1 &
# wallpaper
[ -f "${XDG_CONFIG_HOME}/wall.jpg" ] && feh --no-fehbg --bg-fill ~/.config/wall.jpg >"${LOG}" 2>&1 &

# screensaver
xset s 300 &
xss-lock -l -- xsecurelock &

# disable energy star
xset -dpms &
# no bell
xset b off &
# no key click
xset c off &
# disable capslock
setxkbmap -option "ctrl:nocaps" &

####################################################################
# start things
####################################################################

# less blue light
pidof redshift || redshift -r -l 37.98:-84.47 >"${LOG}" 2>&1 &
# notifications
pidof dunst || dunst >"${LOG}" 2>&1 &
# remove mouse pointer when idle
pidof unclutter || uclutter >"${LOG}" 2>&1 &
# status bar
pidof polybar || {
  polybar default >"${LOG}" 2>&1 &
  if xrandr -q | grep -q "${MON2} connected"; then
    polybar extra >"${LOG}" 2>&1 &
  fi
}

####################################################################
# bspwm config
####################################################################

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

bspc config window_gap "${WM_GAP}"
bspc config top_padding $((PANEL_HEIGHT + 5))

# list displays with `xrandr --query`
# single display:
# bspc monitor -d 1 2 3 4 5 6 7 8 9 10
# multi display:
bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7
bspc monitor HDMI-A-0 -d 8 9 0

bspc config borderless_monocle true
bspc config single_monocle true
bspc config paddingless_monocle true
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
# caused alignment issues...
bspc config honor_size_hints false
#bspc config ignore_ewmh_focus true

# color settings
bspc config presel_feedback_color "#1ABB9B"
bspc config focused_border_color "#7DAEA3"
bspc config normal_border_color "#45707a"
bspc config border_width "${LINE_WIDTH}"

bspc config focus_follows_pointer true
#bspc config pointer_follows_focus true

#Settings for manual splitting
#bspc config split_ratio 0.52
bspc config split_ratio 0.50

#bspc rule -a screenkey --unmanage
#bspc rule -a lxterminal state=floating center=true sticky=true
#bspc rule -a firefox private=on
#bspc rule -a chromium private=on
bspc rule -a Gimp state=floating follow=on
bspc rule -a mpv state=floating layer=normal
bspc rule -a libreoffice state=tiled layer=normal
bspc rule -a Peek state=floating follow=on
#bspc desktop 10 --layout monocle

# external rules
bspc config external_rules_command "${HOME}/.bin/bspwm-ext"
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command /usr/bin/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command /usr/bin/adjust-new-window
