#!/bin/bash

# list discovered fonts: fc-list
# see font paths: xset q
find /usr/share/fonts ~/.local/share/fonts -name fonts.dir | while read -r dir; do
    xset +fp "$(dirname "${dir}")"
done
xset fp rehash &
fc-cache -fv &

xsetroot -cursor_name left_ptr &
# don't background to avoid race bugs
xrdb -merge .Xresources
# wallpaper
feh --no-fehbg --bg-fill ~/.config/wallpaper/triangles.jpg &

# screensaver
xset s 600 &
xss-lock -l -- xsecurelock &

# disable energy star
xset -dpms &
# no bell
xset b off &
# no key click
xset c off &
# disable capslock
setxkbmap -option "ctrl:nocaps" &

# compositing
pidof picom || picom -b &
# less blue light
pidof redshift || redshift -r -l 37.98:-84.47 &
# notifications
pidof dunst || dunst &
# remove mouse pointer when idle
pidof unclutter || uclutter &
# status bar
pidof polybar || polybar default &

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config window_gap 10
bspc config top_padding 35
bspc config border_width 2

bspc config borderless_monocle true
bspc config single_monocle true
# bspc config paddingless_monocle true
# bspc config gapless_monocle true
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# caused alignment issues...
bspc config honor_size_hints false
#bspc config ignore_ewmh_focus true

# color settings
bspc config presel_feedback_color "#1ABB9B"
bspc config focused_border_color "#7DAEA3"
bspc config normal_border_color "#45707a"

bspc config focus_follows_pointer true
#bspc config pointer_follows_focus true

#Settings for manual splitting
#bspc config split_ratio 0.52
bspc config split_ratio 0.50

#bspc rule -a screenkey --unmanage
#bspc rule -a lxterminal state=floating center=true sticky=true
bspc rule -a chromium private=on
bspc rule -a Gimp desktop='^7' state=floating
bspc rule -a libreoffice desktop='^7' state=floating layer=normal
bspc rule -a mpv state=floating layer=normal
bspc rule -a Peek state=floating follow=on
bspc rule -a Slack desktop='^8'
bspc rule -a Spotify desktop='^9'
bspc rule -a zoom state=floating follow=on
# bspc desktop 10 --layout monocle

# external rules
# bspc config external_rules_command "${HOME}/.bin/bspwm-ext"
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command /usr/bin/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command /usr/bin/adjust-new-window
