# Kanagawa Dragon (https://github.com/rebelot/kanagawa.nvim)
# Used by hyprtoolkit apps: hyprlauncher, hyprpolkitagent, etc.

# dragonBlack0
background = 0xFF0D0C0C
# dragonBlack3
base = 0xFF181616
# dragonWhite
text = 0xFFC5C9C5
# dragonBlack4
alternate_base = 0xFF282727
# fujiWhite
bright_text = 0xFFDCD7BA
# dragonBlue2
accent = 0xFF8BA4B0
accent_secondary = 0xFF8BA4B0

font_family = SauceCodePro Nerd Font Mono
font_family_monospace = SauceCodePro Nerd Font Mono
