# blue
#background = 0xFF11111B
#base = 0xFF1E1E2E
#text = 0xFFCDD6F4
#alternate_base = 0xFF181825
#bright_text = 0xFFF5E0DC
#accent = 0xFF89B4FA
#accent_secondary = 0xFF89B4FA

# sky
background = 0xFF11111B
base = 0xFF1E1E2E
text = 0xFFCDD6F4
alternate_base = 0xFF181825
bright_text = 0xFFF5E0DC
accent = 0xFF89DCEB
accent_secondary = 0xFF89DCEB
