$font = SauceCodePro Nerd Font Mono

$background = rgb(16161d)
$border = rgb(54546d)
$text = rgb(c8c093)
$red = rgb(c34043)
$yellow = rgb(dca561)

# GENERAL
general {
  disable_loading_bar = true
  hide_cursor = true
}

# BACKGROUND
background {
  monitor =
  path = ~/.config/wallpaper/kanagawa.jpg
  blur_passes = 2
  color = $background
}

# TIME
label {
  monitor =
  text = cmd[update:30000] echo "$(date +"%R")"
  color = $text
  font_size = 90
  font_family = $font
  position = -30, 0
  halign = right
  valign = top
}

# DATE
label {
  monitor =
  text = cmd[update:43200000] echo "$(date +"%A, %d %B %Y")"
  color = $text
  font_size = 24
  font_family = $font
  position = -30, -150
  halign = right
  valign = top
}

# AVATAR
image {
  monitor = 
  path = ~/Pictures/avatar.png
  size = 100
  border_color = $border
  position = 0, 75
  halign = center
  valign = center
}

# INPUT FIELD
input-field {
  monitor =
  size = 300, 60
  outline_thickness = 2
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = $border
  inner_color = $background
  font_color = $text
  fade_on_empty = false
  # placeholder_text = <span foreground="##$textAlpha"><i>󰌾 Logged in as </i><span foreground="##$accentAlpha">$USER</span></span>
  # placeholder_text = ...
  placeholder_text =
  hide_input = false
  check_color = $border
  fail_color = $red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $yellow
  position = 0, -35
  halign = center
  valign = center
}
